
CREATE SCHEMA `ems` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;


CREATE TABLE IF NOT EXISTS `ems`.`employees` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email_id` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci